### ISSUE TITLE
about ssc

### ISSUE THREAD

**Issue by scriptvpskita** [liberize/ssc#39]
i really love your job

anyway i want to ask you questions.
how to change /fd/3 to another path ?

**Comment by liberize** [comment]
I see only one way to do this, create a symlink to /dev/fd/3 and pass it to the interpreter.
There are some limitations though, you cannot use the same name as your binary because the symlink are created at current directory unless an absolute path is specified. You can use /tmp/xxx or .xxx of course.

**Comment by liberize** [comment]
added -n flag.
